version: '3.7'

services:

    mlflow:
      build:
        context: .
        dockerfile: Dockerfile.mlflow
      ports:
        - "5000:5000"
      volumes:
        - mlflow-data:/mlflow

    api:
      build:
        context: app
      environment:
        MLFLOW_URI: http://mlflow:5000
        MODEL_URI: models:/Reggaeton_Classifier_V1.0/latest
      ports:
      - "8001:15400"
      depends_on:
        - mlflow
volumes:
  mlflow-data:
  postgres-db-volume: